esphome:
  name: pvs-minimal
  friendly_name: Minimal PVS Monitor

esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "15"
  board: esp32dev

api:

external_components:
  - source: github://pr#3256
    components: [ http_request ]
  - source:
      type: local
      path: ../components
    components:
      - sunpower_solar_pvs

sunpower_solar_pvs:
  id: solar
  serial: PVS1
  consumption_meter:
    serial: CM1
  production_meter:
    serial: PM1

sensor:
  - platform: sunpower_solar_pvs

    energy_from_grid: Energy From Grid
    energy_to_grid: Energy To Grid

    consumption_meter:
      lifetime_energy:
        name: Consumption Lifetime Energy
        internal: true

    production_meter:
      lifetime_energy: Production Lifetime Energy

http_request:
  id: pvs_data
  useragent: esphome/pvs
  rx_buffer_size: 35000

time:
  - id: homeassistant_time
    platform: homeassistant
    timezone: EST5EDT,M3.2.0,M11.1.0
    on_time:
      - seconds: 45
        minutes: '*'
        then:
          - http_request.get:
              url: http://172.27.153.1/cgi-bin/dl_cgi?Command=DeviceList
              capture_response: true
              on_response:
                then:
                  - delay: 3s
                  - lambda: id(solar).process_data(response.data);
